# Generated by Django 4.2.4 on 2023-08-17 18:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('alias', models.CharField(blank=True, db_index=True, default='', help_text='Page URL. For example: about-us.', max_length=255, verbose_name='Alias')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('introtext', models.TextField(blank=True, null=True, verbose_name='Introductory Text')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser Window Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('alias', models.CharField(blank=True, db_index=True, default='', help_text='Page URL. For example: about-us.', max_length=255, verbose_name='Alias')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('introtext', models.TextField(blank=True, null=True, verbose_name='Introductory Text')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser Window Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.slider')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
