# Generated by Django 4.2.3 on 2023-08-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'страница', 'verbose_name_plural': 'страницы'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'слайдер', 'verbose_name_plural': 'слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='slideritem',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
