# Generated by Django 4.2.3 on 2023-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_news_city_page_city_slider_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='city',
            field=models.CharField(choices=[('ekaterinburg', 'Екатеринбург'), ('ufa', 'Уфа'), ('sant-peterburg', 'Санкт-Петербург'), ('tyumen', 'Тюмень'), ('magadan', 'Магадан'), ('kursk', 'Курская область'), ('mahachkala', 'Махачкала')], default='ufa', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='page',
            name='city',
            field=models.CharField(choices=[('ekaterinburg', 'Екатеринбург'), ('ufa', 'Уфа'), ('sant-peterburg', 'Санкт-Петербург'), ('tyumen', 'Тюмень'), ('magadan', 'Магадан'), ('kursk', 'Курская область'), ('mahachkala', 'Махачкала')], default='ufa', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='city',
            field=models.CharField(choices=[('ekaterinburg', 'Екатеринбург'), ('ufa', 'Уфа'), ('sant-peterburg', 'Санкт-Петербург'), ('tyumen', 'Тюмень'), ('magadan', 'Магадан'), ('kursk', 'Курская область'), ('mahachkala', 'Махачкала')], default='ufa', max_length=100, verbose_name='City'),
        ),
    ]
