# Generated by Django 4.2.3 on 2023-09-19 19:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(choices=[('ekaterinburg', 'Екатеринбург'), ('ufa', 'Уфа'), ('sant-peterburg', 'Санкт-Петербург'), ('tyumen', 'Тюмень'), ('magadan', 'Магадан'), ('kursk', 'Курская область'), ('mahachkala', 'Махачкала')], default='ufa', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ekaterinburg', 'Екатеринбург'), ('ufa', 'Уфа'), ('sant-peterburg', 'Санкт-Петербург'), ('tyumen', 'Тюмень'), ('magadan', 'Магадан'), ('kursk', 'Курская область'), ('mahachkala', 'Махачкала')], default='ufa', max_length=100, verbose_name='City'),
        ),
    ]
